[package]
name = "sched"
version = "0.1.0"
authors = ["Gopa Kumar <gopakumarce@gmail.com>"]
edition = "2018"

[dependencies]
crossbeam-queue = "0.2.1"
common = { path = "../common" }
packet = { path = "../packet" }
counters = { path = "../counters" }
msg = { path = "../msg" }
