[package]
name = "graph"
version = "0.1.0"
authors = ["Gopa Kumar <gopakumarce@gmail.com>"]
edition = "2018"

[dependencies]
crossbeam-queue = "0.2.1"
names = { path = "../names" }
packet = { path = "../packet" }
counters = { path = "../counters" }
log = { path = "../log" }
